# sops-nix configuration
# Replace AGE_PUBLIC_KEY with your key from: age-keygen -o ~/.config/sops/age/keys.txt
#
# Usage:
#   1. Generate key: age-keygen -o ~/.config/sops/age/keys.txt
#   2. Copy public key (starts with age1...) to this file
#   3. Create secrets: sops secrets/secrets.yaml
#   4. Uncomment defaultSopsFile in modules/tools/security.nix
#
keys:
  - &anko age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *anko
