[default.extend-words]
# keep-sorted start
DED = "DED"
MAPE = "MAPE"
acn = "acn"
ags = "ags"
braket = "braket"
earch = "earch"
hm = "hm"
ist = "ist"
nix = "nix"
noice = "noice"
ot = "ot"
uffer = "uffer"
# keep-sorted end

[files]
extend-exclude = [
  # keep-sorted start
  "*.gif",
  "*.jpg",
  "*.lock",
  "*.png",
  ".direnv/",
  "flake.lock",
  "result",
  # keep-sorted end
]
