- hosts: localhost
  connection: local

  tasks:
    - import_tasks: files.yml
      tags:
        - files

    - import_tasks: asdf.yaml
      tags:
        - asdf

    - import_tasks: brew.yml
      tags:
        - brew

    - import_tasks: winget.yml
      tags:
        - winget

    - import_tasks: pip.yml
      tags:
        - pip

    - import_tasks: npm.yml
      tags:
        - npm

    - import_tasks: go.yml
      tags:
        - go

    - import_tasks: launchd.yml
      tags:
        - launchd

    - import_tasks: sudoers.yml
      tags:
        - sudoers

    - import_tasks: apt.yaml
      tags:
        - apt

