# Package definitions for bootstrap
# Format: package = "name" or package = { name = "actual-name", optional = true }

[base]
# Essential tools needed everywhere
packages = [
    "git",
    "curl", 
    "wget",
    "tree",
    "jq",
    "yq",
]

[shell]
# Shell and terminal tools
packages = [
    "tmux",
    "zsh",
    { name = "fish", optional = true },
]

[modern-cli]
# Modern replacements for standard CLI tools
packages = [
    "ripgrep",  # Better grep
    "fd",       # Better find  
    "bat",      # Better cat
    "fzf",      # Fuzzy finder
    "gh",       # GitHub CLI
    "eza",      # Better ls
    "zoxide",   # Better cd
    "starship", # Prompt
    "gomi",     # Better rm
    "atuin",    # Shell history
]

[terminal]
# Terminal multiplexers and emulators
packages = [
    { name = "zellij", optional = true },
]

[development]
# Development tools and editors
packages = [
    "vim",
    "neovim",
    "mise",  # Version manager
]

[languages]
# Programming languages (managed by mise, but needed for bootstrap)
packages = [
    { name = "node", optional = true },
    { name = "python", optional = true },
    { name = "ruby", optional = true },
    { name = "go", optional = true },
    { name = "rust", optional = true },
]

[security]
# Security and secrets management
packages = [
    "git-secrets",
    { name = "1password-cli", macos = "1password-cli", linux = "1password-cli" },
    { name = "gnupg", optional = true },
    { name = "pass", optional = true },
]

[ai]
# AI development tools
npm_packages = [
    "aicommits",
]
gh_extensions = [
    "github/gh-copilot",
]

[utilities]
# Optional utilities
packages = [
    { name = "htop", optional = true },
    { name = "ncdu", optional = true },
    { name = "tldr", optional = true },
    { name = "ffmpeg", optional = true },
    { name = "imagemagick", optional = true },
    { name = "pandoc", optional = true },
]

[macos]
# macOS specific tools
packages = [
    { name = "yabai", optional = true },  # Window manager
]

casks = [
    { name = "visual-studio-code", optional = true },
    { name = "iterm2", optional = true },
    { name = "warp", optional = true },
    { name = "raycast", optional = true },
    { name = "rectangle", optional = true },
]

[linux]
# Linux specific packages
packages = [
    { name = "build-essential", distro = "ubuntu" },
    { name = "base-devel", distro = "arch" },
]

# Version overrides for manual installations
[versions]
ripgrep = "13.0.0"
fd = "v8.7.0"
bat = "v0.23.0"