# mise configuration

[tools]
# Core languages
node = "lts"
python = "latest"
ruby = "latest"
go = "latest"
rust = "latest"
deno = "latest"
bun = "latest"

# Package managers
pnpm = "latest"

# Additional tools
fzf = "latest"
fd = "latest"

# Development workflow tools
direnv = "latest"      # Environment variable management
just = "latest"        # Modern make alternative
watchexec = "latest"   # File watcher

# Code quality tools
# Python tools are now managed by uv

# Global npm packages
"npm:@antfu/ni" = "latest"               # Package manager agnostic commands
"npm:@anthropic-ai/claude-code" = "latest" # Claude Code CLI

[settings]
# Automatically install missing tools
experimental = true
# Use .node-version, .python-version etc
legacy_version_file = true
