# mise configuration

[tools]
# Core languages
node = "lts"
python = "latest"
ruby = "latest"
go = "latest"
rust = "latest"
deno = "latest"
bun = "latest"

# Package managers
pnpm = "latest"

# Additional tools
fzf = "latest"
fd = "latest"

# Development workflow tools
direnv = "latest"      # Environment variable management
just = "latest"        # Modern make alternative
watchexec = "latest"   # File watcher

# Code quality tools
# Python tools are now managed by uv

# GitHub CLI extensions are installed separately via gh
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
# npm-check-updates
# figma-developer-mcp
# ccusage
# @google/gemini-cli

[settings]
# Automatically install missing tools
experimental = true
# Use .node-version, .python-version etc
legacy_version_file = true
