- name: update homebrew
  community.general.homebrew:
  update_homebrew: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - ansible
      - anyenv
      - bat
      - exa
      - fd
      - fish
      - fzf
      - gh
      - ghq
      - git
      - jq
      - lsd
      - mas
      - node
      - procs
      - ripgrep
      - tig
      - tree
      - wget
      - yarn
      - zsh

- name: install homebrew cask packages
  community.general.homebrew_cask:
    name:
      - alfred
      - asana
      - appcleaner
      - discord
      - docker
      - dropbox
      - font-hackgen-nerd
      - google-chrome
      - google-japanese-ime
      - hyperswitch
      - iterm2
      - karabiner-elements
      - ngrok
      - notion
      - postman
      - tableplus
      - visual-studio-code
      - zoom

