- name: Fetch dein
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    return_content: yes
  register: dein_installer

- name: Run dein installer
  ansible.builtin.shell:
    cmd: sh -s -- ~/.cache/dein
    stdin: "{{ dein_installer.content }}"
