- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: apt upgrade
  become: yes
  apt:
    upgrade: yes

- name: install apt base packages
  become: yes
  apt:
    name:
      - git
      - build-essential
      - m4
      - unzip
      - curl
      - pkg-config

        # - name:
        #apt_repository:
        #repo: ppa:fish-shell/release-3

- name: install apt packages
  become: yes
  apt:
    name:
      - opam
      - fish
      - gh # gh browse
        #- fd-find
        # - ripgrep
        # - fzf
        # - tldr
