- name: Install apt base packages
  become: yes
  package:
    name:
      - git
      - build-essential
      - m4
      - unzip
      - curl
      - pkg-config
      - emacs
  tags: base

- name: Install modern commands by apt
  become: yes
  package:
    name:
      - tldr
      - htop
      - gh
      - fzf
  tags: commands

- name: Install zsh and fish
  become: yes
  apt:
    name:
      - zsh
      - fish
  tags: shell

# TODO: pwndbg
- name: Install CTF tools
  become: yes
  apt:
    name:
      - foremost
      - binwalk
      - steghide
      - stepic
      - exiftool
      - john
  tags: ctf

- name: Download pwndbg
  git:
    repo: https://github.com/pwndbg/pwndbg
    dest: ./pwndbg
    clone: yes
    update: yes
  tags: ctf

- name: Install pwndbg
  shell:
    cmd: cd pwndbg; ./setup.sh
  tags: ctf

# ROPgadget
- name: Install pwn
  become: yes
  shell:
    cmd: pip install pwntools patchelf; cargo install pwninit; gem install one_gadget
  tags: ctf
