# Opam
- name: Install ocaml stuff
  become: false
  shell: "{{item}}"
  with_items:
    # - sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
    - opam init
    # - opam switch create 4.14.0
    - eval $(opam env)
    - opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
    # - opam repository add satyrographos https://github.com/na4zagin3/satyrographos-repo.git
    - opam repository add satyrographos-repo https://github.com/na4zagin3/satyrographos-repo.git
    - opam install -y user-setup menhir dune ounit tuareg depext
    - opam user-setup install
    - opam update
  tags: satysfi

# SATySFi
- name: Install SATySFi satyrographos
  become: false
  shell: "{{item}}"
  with_items:
    # - opam depext satysfi satysfi-dist satyrographos
    - opam install -y satysfi satysfi-dist satyrographos
    - satyrographos install
  tags: satysfi

