name: Test Local

on:
  workflow_dispatch:

jobs:
  test-local:
    runs-on: ubuntu-latest
    steps:
      - name: Test with local fixes
        run: |
          # Install yadm
          sudo apt-get update -qq
          sudo apt-get install -y curl git
          curl -fLo /tmp/yadm https://github.com/yadm-dev/yadm/raw/master/yadm
          sudo mv /tmp/yadm /usr/local/bin/yadm
          sudo chmod a+x /usr/local/bin/yadm
          
          # Clone
          rm -f "$HOME/.config/git/config"
          cd "$HOME"
          yadm clone https://github.com/${{ github.repository }}.git --no-bootstrap -f -b ${{ github.ref_name }}
          
          # Set config and run alt
          yadm config local.class ci
          yadm alt
          
          # Fix the local issue in the cloned file
          echo "=== Fixing local usage in install script ==="
          sed -i 's/local apt_tools=/apt_tools=/' "$HOME/.config/yadm/install"
          sed -i 's/local tmp_dir=/tmp_dir=/' "$HOME/.config/yadm/install"
          
          # Also fix mise config
          echo "=== Fixing mise config ==="
          if [[ -f "$HOME/.config/mise/config.toml" ]]; then
            sed -i 's/^not_found_auto_install/# not_found_auto_install/' "$HOME/.config/mise/config.toml"
            sed -i 's/^shims_dir/# shims_dir/' "$HOME/.config/mise/config.toml"
          fi
          
          # Now run bootstrap
          export YADM_BOOTSTRAP=1
          export YADM_SKIP_CONFIG=1
          export YADM_CLASS=ci
          export YADM_BOOTSTRAP_MACOS_SETTINGS=false
          
          echo "=== Running bootstrap ==="
          "$HOME/.config/yadm/bootstrap" || {
            echo "Bootstrap failed with exit code: $?"
            exit 1
          }