# mise global configuration
# https://mise.jdx.dev/configuration.html

[settings]
experimental = true
legacy_version_file = true
jobs = 4
missing_runtime_behavior = "auto_install"
shims_dir = "~/.local/bin"
task_output = "prefix"
not_found_auto_install = true

[env]
PYTHONUNBUFFERED = "1"
NODE_OPTIONS = "--max-old-space-size=4096"

[tools]
# Languages
node = "lts"
ruby = "latest"
go = "latest"
rust = "latest"
uv = "latest"
ruff = "latest"
pnpm = "latest"
deno = "latest"
bun = "latest"

# Development workflow tools
direnv = "latest"      # Environment variable management
just = "latest"        # Modern make alternative
watchexec = "latest"   # File watcher

# Shell tools
shellcheck = "latest"
shfmt = "latest"

# Global npm packages
"npm:aicommits" = "latest"               # AI-powered commit messages
"npm:@antfu/ni" = "latest"               # Package manager agnostic commands
"npm:@anthropic-ai/claude-code" = "latest" # Claude Code CLI

[tasks.update]
description = "Update all tools to latest versions"
run = """
echo "📦 Updating mise tools..."
mise update
mise prune
echo "✅ All tools updated!"
"""

[tasks.doctor]
description = "Check mise configuration and health"
run = """
mise doctor
echo "---"
mise list
"""

[tasks.clean]
description = "Clean up old tool versions"
run = """
echo "🧹 Cleaning up old versions..."
mise prune --yes
echo "✅ Cleanup complete!"
"""

[tasks.sync]
description = "Sync development environment"
depends = ["update"]
run = """
echo "🔄 Syncing environment..."
mise install
echo "✅ Environment synced!"
"""

# Hidden task for completions
[tasks._list_tools]
hide = true
quiet = true
run = "mise list --installed | cut -f1 -d' '"
