# mise global configuration
# https://mise.jdx.dev/configuration.html

[settings]
experimental = true
legacy_version_file = true
jobs = 4
# not_found_auto_install = true
# shims_dir = "~/.local/bin"
task_output = "prefix"

[env]
PYTHONUNBUFFERED = "1"
NODE_OPTIONS = "--max-old-space-size=4096"

[tools]
# Languages
node = "lts"
python = "latest"
ruby = "latest"
go = "latest"
rust = "latest"
pnpm = "latest"
deno = "latest"
bun = "latest"
# Python tools:
# uv is installed via curl/brew in bootstrap
# Other tools can be run with: uvx ruff, uvx black, etc.

# Shell tools
shellcheck = "latest"
shfmt = "latest"

# Global npm packages
"npm:@antfu/ni" = "latest"               # Package manager agnostic commands
"npm:@anthropic-ai/claude-code" = "latest" # Claude Code CLI
"npm:@google/gemini-cli" = "latest"     # Gemini AI CLI

[tasks.update]
description = "Update all tools to latest versions"
run = """
echo "📦 Updating mise tools..."
mise update
mise prune
echo "✅ All tools updated!"
"""

[tasks.doctor]
description = "Check mise configuration and health"
run = """
mise doctor
echo "---"
mise list
"""

[tasks.clean]
description = "Clean up old tool versions"
run = """
echo "🧹 Cleaning up old versions..."
mise prune --yes
echo "✅ Cleanup complete!"
"""

[tasks.sync]
description = "Sync development environment"
depends = ["update"]
run = """
echo "🔄 Syncing environment..."
mise install
echo "✅ Environment synced!"
"""

# Hidden task for completions
[tasks._list_tools]
hide = true
quiet = true
run = "mise list --installed | cut -f1 -d' '"
