[settings]
experimental = true
legacy_version_file = true
jobs = 4
task_output = "prefix"

[env]
PYTHONUNBUFFERED = "1"
NODE_OPTIONS = "--max-old-space-size=4096"

[tools]
node = "lts"
python = "latest"
ruby = "latest"
go = "latest"
rust = "latest"
pnpm = "latest"
deno = "latest"
bun = "latest"

# Lua
lua = "latest"

shellcheck = "latest"
shfmt = "latest"

"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:czg" = "latest"
"npm:cz-git" = "latest"

[tasks.update]
description = "Update all tools to latest versions"
run = """
echo "📦 Updating mise tools..."
mise update
mise prune
echo "✅ All tools updated!"
"""

[tasks.doctor]
description = "Check mise configuration and health"
run = """
mise doctor
echo "---"
mise list
"""

[tasks.clean]
description = "Clean up old tool versions"
run = """
echo "🧹 Cleaning up old versions..."
mise prune --yes
echo "✅ Cleanup complete!"
"""

[tasks.sync]
description = "Sync development environment"
depends = ["update"]
run = """
echo "🔄 Syncing environment..."
mise install
echo "✅ Environment synced!"
"""

[tasks._list_tools]
hide = true
quiet = true
run = "mise list --installed | cut -f1 -d' '"
